//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_PerfumeImages
    {
        public int PerfumeImages_ID { get; set; }
        public Nullable<int> PerfumeImages_Perfume_ID { get; set; }
        public string PerfumeImages_ImageIndex { get; set; }
    
        public virtual Tbl_Perfume Tbl_Perfume { get; set; }
    }
}
