//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_EmailMessage
    {
        public int Email_ID { get; set; }
        public string Email_Subject { get; set; }
        public string Email_Body { get; set; }
        public string Email_Email { get; set; }
        public string Emai_Password { get; set; }
    }
}
