//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Services
    {
        public int Services_ID { get; set; }
        public string Services_Title { get; set; }
        public string Services_Description { get; set; }
        public string Services_ImageIndex { get; set; }
        public Nullable<int> Services_SiteServiceID { get; set; }
    
        public virtual Tbl_SiteService Tbl_SiteService { get; set; }
    }
}
