//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_City()
        {
            this.Tbl_User = new HashSet<Tbl_User>();
        }
    
        public int City_ID { get; set; }
        public string City_Title { get; set; }
        public Nullable<int> City_State_ID { get; set; }
    
        public virtual Tbl_State Tbl_State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_User> Tbl_User { get; set; }
    }
}
