//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CompanySample
    {
        public int CompanySample_ID { get; set; }
        public Nullable<int> CompanySample_Perfume_ID { get; set; }
        public Nullable<int> CompanySample_AllCount { get; set; }
        public Nullable<int> CompanySample_Price { get; set; }
        public Nullable<double> CompanySample_Weight { get; set; }
    
        public virtual Tbl_Perfume Tbl_Perfume { get; set; }
    }
}
