//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_InterimBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_InterimBill()
        {
            this.Tbl_UserBills = new HashSet<Tbl_UserBills>();
        }
    
        public int InterimBill_ID { get; set; }
        public Nullable<System.DateTime> InterimBill_Date { get; set; }
        public Nullable<int> InterimBill_Category_ID { get; set; }
        public Nullable<int> InterimBill_Perfume_ID { get; set; }
        public Nullable<int> InterimBill_Count { get; set; }
        public Nullable<double> InterimBill_Weight { get; set; }
        public Nullable<int> InterimBill_Price { get; set; }
        public Nullable<int> InterimBill_InvoiceNum { get; set; }
        public Nullable<System.DateTime> InterimBill_ExpDate { get; set; }
        public Nullable<int> InterimBill_User_ID { get; set; }
        public Nullable<bool> InterimBill_Status { get; set; }
    
        public virtual Tbl_Category Tbl_Category { get; set; }
        public virtual Tbl_Perfume Tbl_Perfume { get; set; }
        public virtual Tbl_User Tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserBills> Tbl_UserBills { get; set; }
    }
}
