//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Bill()
        {
            this.Tbl_UserBills = new HashSet<Tbl_UserBills>();
        }
    
        public int Bill_ID { get; set; }
        public Nullable<System.DateTime> Bill_Date { get; set; }
        public Nullable<int> Bill_PayPrice { get; set; }
        public Nullable<int> Bill_PostType_ID { get; set; }
        public string Bill_InvoiceNumber { get; set; }
        public Nullable<int> Bill_RefID { get; set; }
        public string Bill_TransNo { get; set; }
        public Nullable<bool> Bill_Status { get; set; }
        public string Bill_TrackingCode { get; set; }
        public string Bill_RefNo { get; set; }
        public Nullable<int> Bill_Off { get; set; }
        public Nullable<int> Bill_OtherPrice { get; set; }
        public Nullable<int> Bill_PostStatus_ID { get; set; }
    
        public virtual Tbl_PostStatus Tbl_PostStatus { get; set; }
        public virtual Tbl_PostType Tbl_PostType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_UserBills> Tbl_UserBills { get; set; }
    }
}
