//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PD_DB : DbContext
    {
        public PD_DB()
            : base("name=PD_DB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Article> Tbl_Article { get; set; }
        public virtual DbSet<Tbl_Bill> Tbl_Bill { get; set; }
        public virtual DbSet<Tbl_Brand> Tbl_Brand { get; set; }
        public virtual DbSet<Tbl_Category> Tbl_Category { get; set; }
        public virtual DbSet<Tbl_City> Tbl_City { get; set; }
        public virtual DbSet<Tbl_Cologne> Tbl_Cologne { get; set; }
        public virtual DbSet<Tbl_CompanySample> Tbl_CompanySample { get; set; }
        public virtual DbSet<Tbl_EmailMessage> Tbl_EmailMessage { get; set; }
        public virtual DbSet<Tbl_HandySample> Tbl_HandySample { get; set; }
        public virtual DbSet<Tbl_InterimBill> Tbl_InterimBill { get; set; }
        public virtual DbSet<Tbl_News> Tbl_News { get; set; }
        public virtual DbSet<Tbl_Perfume> Tbl_Perfume { get; set; }
        public virtual DbSet<Tbl_PerfumeImages> Tbl_PerfumeImages { get; set; }
        public virtual DbSet<Tbl_PerfumeSeason> Tbl_PerfumeSeason { get; set; }
        public virtual DbSet<Tbl_PerfumeType> Tbl_PerfumeType { get; set; }
        public virtual DbSet<Tbl_PostStatus> Tbl_PostStatus { get; set; }
        public virtual DbSet<Tbl_PostType> Tbl_PostType { get; set; }
        public virtual DbSet<Tbl_ResetPasswordRequests> Tbl_ResetPasswordRequests { get; set; }
        public virtual DbSet<Tbl_Role> Tbl_Role { get; set; }
        public virtual DbSet<Tbl_Season> Tbl_Season { get; set; }
        public virtual DbSet<Tbl_Services> Tbl_Services { get; set; }
        public virtual DbSet<Tbl_SiteService> Tbl_SiteService { get; set; }
        public virtual DbSet<Tbl_Slide> Tbl_Slide { get; set; }
        public virtual DbSet<Tbl_State> Tbl_State { get; set; }
        public virtual DbSet<Tbl_User> Tbl_User { get; set; }
        public virtual DbSet<Tbl_UserBills> Tbl_UserBills { get; set; }
    }
}
