//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Article
    {
        public int Article_ID { get; set; }
        public string Article_Title { get; set; }
        public string Article_Path { get; set; }
    }
}
