//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Perfume
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Perfume()
        {
            this.Tbl_Cologne = new HashSet<Tbl_Cologne>();
            this.Tbl_CompanySample = new HashSet<Tbl_CompanySample>();
            this.Tbl_HandySample = new HashSet<Tbl_HandySample>();
            this.Tbl_InterimBill = new HashSet<Tbl_InterimBill>();
            this.Tbl_PerfumeImages = new HashSet<Tbl_PerfumeImages>();
            this.Tbl_PerfumeSeason = new HashSet<Tbl_PerfumeSeason>();
        }
    
        public int Perfume_ID { get; set; }
        public string Perfume_Name { get; set; }
        public Nullable<int> Perfume_Brand_ID { get; set; }
        public string Perfume_ImageIndex { get; set; }
        public string Perfume_Perfumer { get; set; }
        public string Perfume_Country { get; set; }
        public string Perfume_TemperOfPerfume { get; set; }
        public string Perfume_Gender { get; set; }
        public string Perfume_OlfactionGroups { get; set; }
        public Nullable<int> Perfume_Type_ID { get; set; }
        public string Perfume_Notes { get; set; }
        public Nullable<bool> Perfume_SpecialOffer { get; set; }
        public string Perfume_Description { get; set; }
    
        public virtual Tbl_Brand Tbl_Brand { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cologne> Tbl_Cologne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_CompanySample> Tbl_CompanySample { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_HandySample> Tbl_HandySample { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InterimBill> Tbl_InterimBill { get; set; }
        public virtual Tbl_PerfumeType Tbl_PerfumeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PerfumeImages> Tbl_PerfumeImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_PerfumeSeason> Tbl_PerfumeSeason { get; set; }
    }
}
