//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UserBills
    {
        public int UserBills_ID { get; set; }
        public Nullable<int> UserBills_InterimBill_ID { get; set; }
        public Nullable<int> UserBills_Bill_ID { get; set; }
    
        public virtual Tbl_Bill Tbl_Bill { get; set; }
        public virtual Tbl_InterimBill Tbl_InterimBill { get; set; }
    }
}
