//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace perfumedecant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_User()
        {
            this.Tbl_InterimBill = new HashSet<Tbl_InterimBill>();
            this.Tbl_ResetPasswordRequests = new HashSet<Tbl_ResetPasswordRequests>();
        }
    
        public int User_ID { get; set; }
        public string User_NameFamily { get; set; }
        public string User_Username { get; set; }
        public string User_Email { get; set; }
        public string User_Password { get; set; }
        public string User_Address { get; set; }
        public Nullable<int> User_City_ID { get; set; }
        public string User_PostalCode { get; set; }
        public string User_Tel { get; set; }
        public string User_Gender { get; set; }
        public string User_Birthday { get; set; }
        public string User_Mobile { get; set; }
        public Nullable<System.DateTime> User_Date { get; set; }
        public Nullable<bool> User_Active { get; set; }
        public Nullable<int> User_Role_ID { get; set; }
        public string User_NationalCode { get; set; }
        public string User_ImageIndex { get; set; }
    
        public virtual Tbl_City Tbl_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_InterimBill> Tbl_InterimBill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ResetPasswordRequests> Tbl_ResetPasswordRequests { get; set; }
        public virtual Tbl_Role Tbl_Role { get; set; }
    }
}
